name: Publish to GH Pages

on:
  push:
    branches:
      - deployWebsite

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: built-site

      - name: Clean built-site
        run: |
          rm -rf ${GITHUB_WORKSPACE}/built-site/*

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_linux-amd64.tar.gz'
          tar -C /usr/local/bin -zxvf /tmp/hugo.tar.gz hugo

      - name: Build
        run: /usr/local/bin/hugo --cleanDestinationDir --gc

      - name: Deploy to gh-pages
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "Deploying to gh-pages from deployWebsite"
          git push origin gh-pages