title: Tratteria

disableKinds:
  - taxonomy
  - taxonomyTerm

enableGitInfo: true

caches:
  assets:
    dir: ':cacheDir/_gen'
    maxAge: -1
  getcsv:
    dir: ':cacheDir/:project'
    maxAge: 60s
  getjson:
    dir: ':cacheDir/:project'
    maxAge: 60s
  images:
    dir: ':cacheDir/_images'
    maxAge: -1
  modules:
    dir: ':cacheDir/modules'
    maxAge: -1

markup:
  highlight:
    style: paraiso-dark

params:
  projectName: Tratteria
  font_awesome_version: 5.12.0
  description: Boilerplate for building beautiful websites
  favicon: favicon.svg
  repositoryUrl: 'https://github.com/SGNL-ai/Tratteria'
  contentDir: /content/
  logos:
    navbar: rectangular-logo.svg
  social:
    - name: GitHub
      color: '#000000'
      url: 'https://github.com/SGNL-ai/Tratteria'
      icon: fab fa-github
  fonts:
    - name: Roboto
      sizes:
        - 400
        - 500
        - 700
      type: heading_font
    - name: Open Sans
      sizes:
        - 400
        - 600
        - 700
      type: sans_serif

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Documentation
      url: /docs/
      weight: 2
